# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=350)),
                ('user_email', models.CharField(max_length=350)),
                ('receiver_email', models.CharField(max_length=350)),
                ('email_subject', models.TextField()),
                ('email_body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=350)),
                ('user_number', models.CharField(max_length=350)),
                ('receiver_number', models.CharField(max_length=350)),
                ('mess_body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
