# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepypro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('campaign_name', models.CharField(blank=True, max_length=350)),
                ('api_key', models.CharField(max_length=350)),
            ],
        ),
        migrations.RenameField(
            model_name='useremail',
            old_name='api_key',
            new_name='sender_email',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='api_key',
            new_name='sender_number',
        ),
        migrations.RemoveField(
            model_name='useremail',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user_number',
        ),
        migrations.AddField(
            model_name='useremail',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='pepypro.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pepypro.User'),
            preserve_default=False,
        ),
    ]
