# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepypro', '0002_auto_20191111_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='user',
        ),
        migrations.AddField(
            model_name='useremail',
            name='api_key',
            field=models.CharField(default=2, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremail',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='useremail',
            name='user_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='api_key',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_name',
            field=models.CharField(default=22, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
