# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepypro', '0003_auto_20191111_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
    ]
